OPAL_INSTALL_DIR=/home/ina/dev/conf
LINUX_BIT=lib_linux_x86_64
PTLIBDIR=${OPAL_INSTALL_DIR}/ptlib
PTLIB_LIB_DIR=${OPAL_INSTALL_DIR}/ptlib
OPALDIR=${OPAL_INSTALL_DIR}/opal
LD_LIBRARY_PATH=${PTLIBDIR}/${LINUX_BIT}:${OPALDIR}/${LINUX_BIT}
PTLIBPLUGINDIR=${PTLIBDIR}/${LINUX_BIT}:${OPALDIR}/${LINUX_BIT}
PKG_CONFIG_PATH=${PTLIBDIR}:${OPALDIR}
