INSTALL_DIR=/usr/local
SUBVERSION=14_3
export PKG_CONFIG_PATH=${INSTALL_DIR}/lib/pkgconfig
export LD_LIBRARY_PATH=${INSTALL_DIR}/lib
export PTLIBPLUGINDIR=${INSTALL_DIR}/lib/ptlib:${INSTALL_DIR}/lib/opal
