OPAL_INSTALL_DIR=/
LINUX_BIT=lib_linux_$(uname -m)
export PTLIBDIR=${OPAL_INSTALL_DIR}/ptlib
export OPALDIR=${OPAL_INSTALL_DIR}/opal
export LD_LIBRARY_PATH=${PTLIBDIR}/${LINUX_BIT}:${OPALDIR}/${LINUX_BIT}
export PTLIBPLUGINDIR=${PTLIBDIR}/${LINUX_BIT}:${OPALDIR}/${LINUX_BIT}
export PKG_CONFIG_PATH=${PTLIBDIR}:${OPALDIR}
